// Common
export const LOADING_DATA_START = "LOADING_DATA_START";
export const LOADING_DATA_STOP = "LOADING_DATA_STOP";

// Homepage
export const GET_HOMEPAGE_DATA_PRISMIC = "GET_HOMEPAGE_DATA_PRISMIC";

// Articles
export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES";
export const SET_ERROR_ALL_ARTICLES_TRUE = "SET_ERROR_ALL_ARTICLES_TRUE";
export const SET_ERROR_ALL_ARTICLES_FALSE = "SET_ERROR_ALL_ARTICLES_FALSE";

// Single Article
export const GET_ARTICLE_BY_UID = "GET_ARTICLE_BY_UID";
export const GET_3_LAST_ARTICLES = "GET_3_LAST_ARTICLES";
export const SET_ERROR_SINGLE_ARTICLE_TRUE = "SET_ERROR_SINGLE_ARTICLE_TRUE";
// export const SET_ERROR_SINGLE_ARTICLE_FALSE = "SET_ERROR_SINGLE_ARTICLE_FALSE";
export const SET_CURRENT_ARTICLE_UID = "SET_CURRENT_ARTICLE_UID";

// Author
export const GET_AUTHOR_BY_UID = "GET_AUTHOR_BY_UID";
export const SET_ERROR_AUTHOR_BY_UID_TRUE = "ERROR_AUTHOR_BY_UID_TRUE";
//export const SET_ERROR_AUTHOR_BY_UID_FALSE = "SET_ERROR_AUTHOR_BY_UID_FALSE";

// Search
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const GET_ARTICLES_BY_SEARCH_TEXT = "GET_ARTICLES_BY_SEARCH_TEXT";
export const SET_LOADING_SEARCH_START = "SET_LOADING_SEARCH_START";
export const SET_LOADING_SEARCH_STOP = "SET_LOADING_SEARCH_STOP";
export const SET_ERROR_SEARCH_TEXT_TRUE = "SET_ERROR_SEARCH_TEXT_TRUE";
export const SET_ERROR_SEARCH_TEXT_FALSE = "SET_ERROR_SEARCH_TEXT_FALSE";
